#!/bin/sh

# script/setup: Set up application for the first time after cloning, or set it back to the initial first unused state.

# -e or errexit causes the script to exit immediately if any command returns a non-zero exit status.
set -e

cd "$(dirname "$0")/.."

script/bootstrap

bin/setup-crons

echo "==> Scripts are now ready to go!"
